http:
  services:
    omeka-classic:
      loadBalancer:
        servers:
          - url: "http://omeka-classic:80"
  routers:
    omeka-classic-web:
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - web
      service: omeka-classic
