---
services:
  omeka-classic:
    environment:
      LIBOPS_SMTP_HOST: mailpit
      LIBOPS_SMTP_PORT: "1025"
  mariadb:
    ports:
      - "3306:3306"
  mailpit:
    image: axllent/mailpit:v1.31@sha256:74d609a42ec279aa63c6b4622a6fa9b5408d1ad5b1d76a1c4be40a265ce0863d
    ports:
      - "1025:1025"
      - "8025:8025"
